import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

const require = createRequire(import.meta.url);
const prismGlobalScript = readFileSync(require.resolve("prismjs/prism.js"), "utf8");

export default defineConfig({
  plugins: [
    {
      name: "virtari-prism-global",
      transformIndexHtml() {
        return [
          {
            tag: "script",
            attrs: { "data-prism-global": "true" },
            children: prismGlobalScript,
            injectTo: "head-prepend",
          },
        ];
      },
    },
    react(),
  ],
  define: {
    // @lexical/code imports Prism language files that read a global `Prism`.
    Prism: "globalThis.Prism",
  },
  server: {
    allowedHosts: true,
    // Honour the port the launcher assigns. Editor preview panes (and most
    // dev-server supervisors) pick a free port, export it as PORT, and then
    // open a browser there — but plain `vite` ignores PORT and picks its own,
    // falling back to 5174+ whenever 5173 is taken by another project. The
    // pane then points at a port nothing is listening on, which shows up as a
    // blank white page rather than an error. Undefined keeps Vite's default
    // behaviour when PORT is not set.
    port: process.env.PORT ? Number(process.env.PORT) : undefined,
  },
  resolve: {
    // Explicit aliases bypass Vite's exports-field resolver, which sporadically
    // fails on workspace packages when new consumer files add imports. Order
    // matters: more specific subpaths must appear BEFORE the bare package name.
    alias: [
      { find: /^@virtari-packages\/primitives\/switch$/, replacement: fileURLToPath(new URL("../../packages/primitives/src/switch/index.ts", import.meta.url)) },
      { find: /^@virtari-packages\/primitives\/checkbox$/, replacement: fileURLToPath(new URL("../../packages/primitives/src/checkbox/index.ts", import.meta.url)) },
      { find: /^@virtari-packages\/primitives\/radio-group$/, replacement: fileURLToPath(new URL("../../packages/primitives/src/radio-group/index.ts", import.meta.url)) },
      { find: /^attr-accept$/, replacement: fileURLToPath(new URL("./src/shims/attrAccept.ts", import.meta.url)) },
      { find: /^prop-types$/, replacement: fileURLToPath(new URL("./src/shims/propTypes.ts", import.meta.url)) },
      { find: /^file-selector$/, replacement: fileURLToPath(new URL("../../node_modules/.pnpm/file-selector@2.1.2/node_modules/file-selector/dist/es2015/index.js", import.meta.url)) },
      { find: /^react-dropzone$/, replacement: fileURLToPath(new URL("../../node_modules/.pnpm/react-dropzone@14.4.1_react@19.2.5/node_modules/react-dropzone/dist/es/index.js", import.meta.url)) },
      { find: /^use-sync-external-store\/shim\/with-selector(?:\.js)?$/, replacement: fileURLToPath(new URL("./src/shims/useSyncExternalStoreWithSelector.ts", import.meta.url)) },
      { find: /^use-sync-external-store\/shim(?:\/index\.js)?$/, replacement: fileURLToPath(new URL("./src/shims/useSyncExternalStoreShim.ts", import.meta.url)) },
      { find: /^@uiw\/react-codemirror$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@uiw/react-codemirror", import.meta.url)) },
      { find: /^@codemirror\/state$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/state", import.meta.url)) },
      { find: /^@codemirror\/view$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/view", import.meta.url)) },
      { find: /^@codemirror\/language$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/language", import.meta.url)) },
      { find: /^@codemirror\/commands$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/commands", import.meta.url)) },
      { find: /^@codemirror\/search$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/search", import.meta.url)) },
      { find: /^@codemirror\/autocomplete$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/autocomplete", import.meta.url)) },
      { find: /^@codemirror\/lint$/, replacement: fileURLToPath(new URL("../../node_modules/.pnpm/@codemirror+lint@6.9.5/node_modules/@codemirror/lint", import.meta.url)) },
      { find: /^@codemirror\/theme-one-dark$/, replacement: fileURLToPath(new URL("../../node_modules/.pnpm/@codemirror+theme-one-dark@6.1.3/node_modules/@codemirror/theme-one-dark", import.meta.url)) },
      { find: /^@codemirror\/lang-javascript$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-javascript", import.meta.url)) },
      { find: /^@codemirror\/lang-css$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-css", import.meta.url)) },
      { find: /^@codemirror\/lang-html$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-html", import.meta.url)) },
      { find: /^@codemirror\/lang-json$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-json", import.meta.url)) },
      { find: /^@codemirror\/lang-markdown$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-markdown", import.meta.url)) },
      { find: /^@codemirror\/lang-python$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-python", import.meta.url)) },
      { find: /^@codemirror\/lang-go$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-go", import.meta.url)) },
      { find: /^@codemirror\/lang-rust$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-rust", import.meta.url)) },
      { find: /^@codemirror\/lang-sql$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-sql", import.meta.url)) },
      { find: /^@codemirror\/lang-yaml$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-yaml", import.meta.url)) },
      { find: /^@codemirror\/lang-xml$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@codemirror/lang-xml", import.meta.url)) },
      { find: /^@lezer\/highlight$/, replacement: fileURLToPath(new URL("../../packages/react-code/node_modules/@lezer/highlight", import.meta.url)) },
      { find: "@virtari-packages/react-button/styles/effects", replacement: fileURLToPath(new URL("../../packages/react-button/src/effects.css", import.meta.url)) },
      { find: "@virtari-packages/react-button/styles/animations", replacement: fileURLToPath(new URL("../../packages/react-button/src/animations.css", import.meta.url)) },
      { find: "@virtari-packages/react-button/styles", replacement: fileURLToPath(new URL("../../packages/react-button/src/Button.css", import.meta.url)) },
      { find: "@virtari-packages/react-button/tokens", replacement: fileURLToPath(new URL("../../packages/react-button/src/Button.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-button", replacement: fileURLToPath(new URL("../../packages/react-button/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-button-group/styles", replacement: fileURLToPath(new URL("../../packages/react-button-group/src/ButtonGroup.css", import.meta.url)) },
      { find: "@virtari-packages/react-button-group/tokens", replacement: fileURLToPath(new URL("../../packages/react-button-group/src/ButtonGroup.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-button-group", replacement: fileURLToPath(new URL("../../packages/react-button-group/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-data-table/styles", replacement: fileURLToPath(new URL("../../packages/react-data-table/src/DataTable.css", import.meta.url)) },
      { find: "@virtari-packages/react-data-table/tokens", replacement: fileURLToPath(new URL("../../packages/react-data-table/src/DataTable.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-data-table/dnd", replacement: fileURLToPath(new URL("../../packages/react-data-table/src/index.dnd.ts", import.meta.url)) },
      { find: "@virtari-packages/react-data-table", replacement: fileURLToPath(new URL("../../packages/react-data-table/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-pagination/styles", replacement: fileURLToPath(new URL("../../packages/react-pagination/src/Pagination.css", import.meta.url)) },
      { find: "@virtari-packages/react-pagination/tokens", replacement: fileURLToPath(new URL("../../packages/react-pagination/src/Pagination.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-pagination", replacement: fileURLToPath(new URL("../../packages/react-pagination/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-form/styles", replacement: fileURLToPath(new URL("../../packages/react-form/src/Form.css", import.meta.url)) },
      { find: "@virtari-packages/react-form/tokens", replacement: fileURLToPath(new URL("../../packages/react-form/src/Form.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-form", replacement: fileURLToPath(new URL("../../packages/react-form/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-file-upload/styles", replacement: fileURLToPath(new URL("../../packages/react-file-upload/src/FileUpload.css", import.meta.url)) },
      { find: "@virtari-packages/react-file-upload/tokens", replacement: fileURLToPath(new URL("../../packages/react-file-upload/src/FileUpload.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-file-upload", replacement: fileURLToPath(new URL("../../packages/react-file-upload/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-command/styles", replacement: fileURLToPath(new URL("../../packages/react-command/src/Command.css", import.meta.url)) },
      { find: "@virtari-packages/react-command/tokens", replacement: fileURLToPath(new URL("../../packages/react-command/src/Command.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-command", replacement: fileURLToPath(new URL("../../packages/react-command/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-tree-view/styles", replacement: fileURLToPath(new URL("../../packages/react-tree-view/src/TreeView.css", import.meta.url)) },
      { find: "@virtari-packages/react-tree-view/tokens", replacement: fileURLToPath(new URL("../../packages/react-tree-view/src/TreeView.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-tree-view", replacement: fileURLToPath(new URL("../../packages/react-tree-view/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-tag-input/styles", replacement: fileURLToPath(new URL("../../packages/react-tag-input/src/TagInput.css", import.meta.url)) },
      { find: "@virtari-packages/react-tag-input/tokens", replacement: fileURLToPath(new URL("../../packages/react-tag-input/src/TagInput.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-tag-input", replacement: fileURLToPath(new URL("../../packages/react-tag-input/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-accordion/styles", replacement: fileURLToPath(new URL("../../packages/react-accordion/src/Accordion.css", import.meta.url)) },
      { find: "@virtari-packages/react-accordion/tokens", replacement: fileURLToPath(new URL("../../packages/react-accordion/src/Accordion.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-accordion", replacement: fileURLToPath(new URL("../../packages/react-accordion/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-alert-dialog/styles", replacement: fileURLToPath(new URL("../../packages/react-alert-dialog/src/AlertDialog.css", import.meta.url)) },
      { find: "@virtari-packages/react-alert-dialog", replacement: fileURLToPath(new URL("../../packages/react-alert-dialog/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-avatar/styles", replacement: fileURLToPath(new URL("../../packages/react-avatar/src/Avatar.css", import.meta.url)) },
      { find: "@virtari-packages/react-avatar", replacement: fileURLToPath(new URL("../../packages/react-avatar/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-badge/styles", replacement: fileURLToPath(new URL("../../packages/react-badge/src/Badge.css", import.meta.url)) },
      { find: "@virtari-packages/react-badge/tokens", replacement: fileURLToPath(new URL("../../packages/react-badge/src/Badge.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-badge", replacement: fileURLToPath(new URL("../../packages/react-badge/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-bottom-nav/styles", replacement: fileURLToPath(new URL("../../packages/react-bottom-nav/src/BottomNav.css", import.meta.url)) },
      { find: "@virtari-packages/react-bottom-nav/tokens", replacement: fileURLToPath(new URL("../../packages/react-bottom-nav/src/BottomNav.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-bottom-nav", replacement: fileURLToPath(new URL("../../packages/react-bottom-nav/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-breadcrumb/styles", replacement: fileURLToPath(new URL("../../packages/react-breadcrumb/src/Breadcrumb.css", import.meta.url)) },
      { find: "@virtari-packages/react-breadcrumb/tokens", replacement: fileURLToPath(new URL("../../packages/react-breadcrumb/src/Breadcrumb.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-breadcrumb", replacement: fileURLToPath(new URL("../../packages/react-breadcrumb/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-card/styles", replacement: fileURLToPath(new URL("../../packages/react-card/src/Card.css", import.meta.url)) },
      { find: "@virtari-packages/react-card", replacement: fileURLToPath(new URL("../../packages/react-card/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-carousel/styles", replacement: fileURLToPath(new URL("../../packages/react-carousel/src/Carousel.css", import.meta.url)) },
      { find: "@virtari-packages/react-carousel/tokens", replacement: fileURLToPath(new URL("../../packages/react-carousel/src/Carousel.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-carousel", replacement: fileURLToPath(new URL("../../packages/react-carousel/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-checkbox/styles", replacement: fileURLToPath(new URL("../../packages/react-checkbox/src/Checkbox.css", import.meta.url)) },
      { find: "@virtari-packages/react-checkbox/tokens", replacement: fileURLToPath(new URL("../../packages/react-checkbox/src/Checkbox.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-checkbox", replacement: fileURLToPath(new URL("../../packages/react-checkbox/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-chip/styles", replacement: fileURLToPath(new URL("../../packages/react-chip/src/Chip.css", import.meta.url)) },
      { find: "@virtari-packages/react-chip/tokens", replacement: fileURLToPath(new URL("../../packages/react-chip/src/Chip.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-chip", replacement: fileURLToPath(new URL("../../packages/react-chip/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-color-picker/styles", replacement: fileURLToPath(new URL("../../packages/react-color-picker/src/ColorPicker.css", import.meta.url)) },
      { find: "@virtari-packages/react-color-picker/tokens", replacement: fileURLToPath(new URL("../../packages/react-color-picker/src/ColorPicker.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-color-picker", replacement: fileURLToPath(new URL("../../packages/react-color-picker/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-code/styles", replacement: fileURLToPath(new URL("../../packages/react-code/src/Code.css", import.meta.url)) },
      { find: "@virtari-packages/react-code/tokens", replacement: fileURLToPath(new URL("../../packages/react-code/src/Code.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-code", replacement: fileURLToPath(new URL("../../packages/react-code/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-copy-button/styles", replacement: fileURLToPath(new URL("../../packages/react-copy-button/src/CopyButton.css", import.meta.url)) },
      { find: "@virtari-packages/react-copy-button/tokens", replacement: fileURLToPath(new URL("../../packages/react-copy-button/src/CopyButton.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-copy-button", replacement: fileURLToPath(new URL("../../packages/react-copy-button/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-collapsible/styles", replacement: fileURLToPath(new URL("../../packages/react-collapsible/src/Collapsible.css", import.meta.url)) },
      { find: "@virtari-packages/react-collapsible", replacement: fileURLToPath(new URL("../../packages/react-collapsible/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/calendar/styles", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/Calendar.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/calendar/tokens", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/Calendar.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/date-field/styles", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/DateField.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/date-field/tokens", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/DateField.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/time-field/styles", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/TimeField.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/time-field/tokens", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/TimeField.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/range-picker/styles", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/DateRangePicker.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/range-picker/tokens", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/DateRangePicker.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/styles", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/DatePicker.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker/tokens", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/DatePicker.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-date-picker", replacement: fileURLToPath(new URL("../../packages/react-date-picker/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-dialog/styles", replacement: fileURLToPath(new URL("../../packages/react-dialog/src/Dialog.css", import.meta.url)) },
      { find: "@virtari-packages/react-dialog/tokens", replacement: fileURLToPath(new URL("../../packages/react-dialog/src/Dialog.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-dialog", replacement: fileURLToPath(new URL("../../packages/react-dialog/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-drawer/styles", replacement: fileURLToPath(new URL("../../packages/react-drawer/src/Drawer.css", import.meta.url)) },
      { find: "@virtari-packages/react-drawer", replacement: fileURLToPath(new URL("../../packages/react-drawer/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-dropdown-menu/styles", replacement: fileURLToPath(new URL("../../packages/react-dropdown-menu/src/DropdownMenu.css", import.meta.url)) },
      { find: "@virtari-packages/react-dropdown-menu", replacement: fileURLToPath(new URL("../../packages/react-dropdown-menu/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-editor/core", replacement: fileURLToPath(new URL("../../packages/react-editor/src/index.core.ts", import.meta.url)) },
      { find: "@virtari-packages/react-editor/styles", replacement: fileURLToPath(new URL("../../packages/react-editor/src/Editor.css", import.meta.url)) },
      { find: "@virtari-packages/react-editor/tokens", replacement: fileURLToPath(new URL("../../packages/react-editor/src/Editor.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-editor", replacement: fileURLToPath(new URL("../../packages/react-editor/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-yoopta-editor/styles", replacement: fileURLToPath(new URL("../../packages/react-yoopta-editor/src/YooptaEditor.css", import.meta.url)) },
      { find: "@virtari-packages/react-yoopta-editor/tokens", replacement: fileURLToPath(new URL("../../packages/react-yoopta-editor/src/YooptaEditor.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-yoopta-editor", replacement: fileURLToPath(new URL("../../packages/react-yoopta-editor/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-empty-state/styles", replacement: fileURLToPath(new URL("../../packages/react-empty-state/src/EmptyState.css", import.meta.url)) },
      { find: "@virtari-packages/react-empty-state/tokens", replacement: fileURLToPath(new URL("../../packages/react-empty-state/src/EmptyState.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-empty-state", replacement: fileURLToPath(new URL("../../packages/react-empty-state/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-fieldset/styles", replacement: fileURLToPath(new URL("../../packages/react-fieldset/src/Fieldset.css", import.meta.url)) },
      { find: "@virtari-packages/react-fieldset/tokens", replacement: fileURLToPath(new URL("../../packages/react-fieldset/src/Fieldset.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-fieldset", replacement: fileURLToPath(new URL("../../packages/react-fieldset/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-flow/styles", replacement: fileURLToPath(new URL("../../packages/react-flow/src/ReactFlow.css", import.meta.url)) },
      { find: "@virtari-packages/react-flow/tokens", replacement: fileURLToPath(new URL("../../packages/react-flow/src/ReactFlow.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-flow", replacement: fileURLToPath(new URL("../../packages/react-flow/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-flag/styles", replacement: fileURLToPath(new URL("../../packages/react-flag/src/Flag.css", import.meta.url)) },
      { find: "@virtari-packages/react-flag/tokens", replacement: fileURLToPath(new URL("../../packages/react-flag/src/Flag.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-flag", replacement: fileURLToPath(new URL("../../packages/react-flag/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-icons/styles", replacement: fileURLToPath(new URL("../../packages/react-icons/src/Icon.css", import.meta.url)) },
      { find: "@virtari-packages/react-icons/tokens", replacement: fileURLToPath(new URL("../../packages/react-icons/src/Icon.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-icons", replacement: fileURLToPath(new URL("../../packages/react-icons/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-input/styles", replacement: fileURLToPath(new URL("../../packages/react-input/src/Input.css", import.meta.url)) },
      { find: "@virtari-packages/react-input", replacement: fileURLToPath(new URL("../../packages/react-input/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-number-input/styles", replacement: fileURLToPath(new URL("../../packages/react-number-input/src/NumberInput.css", import.meta.url)) },
      { find: "@virtari-packages/react-number-input/tokens", replacement: fileURLToPath(new URL("../../packages/react-number-input/src/NumberInput.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-number-input", replacement: fileURLToPath(new URL("../../packages/react-number-input/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-otp-input/styles", replacement: fileURLToPath(new URL("../../packages/react-otp-input/src/OtpInput.css", import.meta.url)) },
      { find: "@virtari-packages/react-otp-input/tokens", replacement: fileURLToPath(new URL("../../packages/react-otp-input/src/OtpInput.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-otp-input", replacement: fileURLToPath(new URL("../../packages/react-otp-input/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-kbd/styles", replacement: fileURLToPath(new URL("../../packages/react-kbd/src/Kbd.css", import.meta.url)) },
      { find: "@virtari-packages/react-kbd", replacement: fileURLToPath(new URL("../../packages/react-kbd/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-label/styles", replacement: fileURLToPath(new URL("../../packages/react-label/src/Label.css", import.meta.url)) },
      { find: "@virtari-packages/react-label", replacement: fileURLToPath(new URL("../../packages/react-label/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-language-picker/styles", replacement: fileURLToPath(new URL("../../packages/react-language-picker/src/LanguagePicker.css", import.meta.url)) },
      { find: "@virtari-packages/react-language-picker/tokens", replacement: fileURLToPath(new URL("../../packages/react-language-picker/src/LanguagePicker.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-language-picker", replacement: fileURLToPath(new URL("../../packages/react-language-picker/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-layout/styles", replacement: fileURLToPath(new URL("../../packages/react-layout/src/index.css", import.meta.url)) },
      { find: "@virtari-packages/react-header/styles", replacement: fileURLToPath(new URL("../../packages/react-header/src/Header.css", import.meta.url)) },
      { find: "@virtari-packages/react-header/tokens", replacement: fileURLToPath(new URL("../../packages/react-header/src/Header.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-nav/styles", replacement: fileURLToPath(new URL("../../packages/react-nav/src/Nav.css", import.meta.url)) },
      { find: "@virtari-packages/react-nav/tokens", replacement: fileURLToPath(new URL("../../packages/react-nav/src/Nav.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-sidebar/styles", replacement: fileURLToPath(new URL("../../packages/react-sidebar/src/Sidebar.css", import.meta.url)) },
      { find: "@virtari-packages/react-sidebar/tokens", replacement: fileURLToPath(new URL("../../packages/react-sidebar/src/Sidebar.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-phone-input/styles", replacement: fileURLToPath(new URL("../../packages/react-phone-input/src/PhoneInput.css", import.meta.url)) },
      { find: "@virtari-packages/react-phone-input/tokens", replacement: fileURLToPath(new URL("../../packages/react-phone-input/src/PhoneInput.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-phone-input", replacement: fileURLToPath(new URL("../../packages/react-phone-input/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-popover/styles", replacement: fileURLToPath(new URL("../../packages/react-popover/src/Popover.css", import.meta.url)) },
      { find: "@virtari-packages/react-popover", replacement: fileURLToPath(new URL("../../packages/react-popover/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-progress/styles", replacement: fileURLToPath(new URL("../../packages/react-progress/src/Progress.css", import.meta.url)) },
      { find: "@virtari-packages/react-progress/tokens", replacement: fileURLToPath(new URL("../../packages/react-progress/src/Progress.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-progress", replacement: fileURLToPath(new URL("../../packages/react-progress/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-radio-group/styles", replacement: fileURLToPath(new URL("../../packages/react-radio-group/src/RadioGroup.css", import.meta.url)) },
      { find: "@virtari-packages/react-radio-group/tokens", replacement: fileURLToPath(new URL("../../packages/react-radio-group/src/RadioGroup.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-radio-group", replacement: fileURLToPath(new URL("../../packages/react-radio-group/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-scroll-area/styles", replacement: fileURLToPath(new URL("../../packages/react-scroll-area/src/ScrollArea.css", import.meta.url)) },
      { find: "@virtari-packages/react-scroll-area/tokens", replacement: fileURLToPath(new URL("../../packages/react-scroll-area/src/ScrollArea.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-scroll-area", replacement: fileURLToPath(new URL("../../packages/react-scroll-area/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-select/combobox/styles", replacement: fileURLToPath(new URL("../../packages/react-select/src/Combobox.css", import.meta.url)) },
      { find: "@virtari-packages/react-select/combobox/tokens", replacement: fileURLToPath(new URL("../../packages/react-select/src/Combobox.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-select/styles", replacement: fileURLToPath(new URL("../../packages/react-select/src/Select.css", import.meta.url)) },
      { find: "@virtari-packages/react-select/tokens", replacement: fileURLToPath(new URL("../../packages/react-select/src/Select.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-select", replacement: fileURLToPath(new URL("../../packages/react-select/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-segmented-control/styles", replacement: fileURLToPath(new URL("../../packages/react-segmented-control/src/SegmentedControl.css", import.meta.url)) },
      { find: "@virtari-packages/react-segmented-control/tokens", replacement: fileURLToPath(new URL("../../packages/react-segmented-control/src/SegmentedControl.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-segmented-control", replacement: fileURLToPath(new URL("../../packages/react-segmented-control/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-separator/styles", replacement: fileURLToPath(new URL("../../packages/react-separator/src/Separator.css", import.meta.url)) },
      { find: "@virtari-packages/react-separator", replacement: fileURLToPath(new URL("../../packages/react-separator/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-skeleton/styles", replacement: fileURLToPath(new URL("../../packages/react-skeleton/src/Skeleton.css", import.meta.url)) },
      { find: "@virtari-packages/react-skeleton", replacement: fileURLToPath(new URL("../../packages/react-skeleton/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-slider/styles", replacement: fileURLToPath(new URL("../../packages/react-slider/src/Slider.css", import.meta.url)) },
      { find: "@virtari-packages/react-slider", replacement: fileURLToPath(new URL("../../packages/react-slider/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-spinner/styles", replacement: fileURLToPath(new URL("../../packages/react-spinner/src/Spinner.css", import.meta.url)) },
      { find: "@virtari-packages/react-spinner/tokens", replacement: fileURLToPath(new URL("../../packages/react-spinner/src/Spinner.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-spinner", replacement: fileURLToPath(new URL("../../packages/react-spinner/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-stepper/styles", replacement: fileURLToPath(new URL("../../packages/react-stepper/src/Stepper.css", import.meta.url)) },
      { find: "@virtari-packages/react-stepper/tokens", replacement: fileURLToPath(new URL("../../packages/react-stepper/src/Stepper.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-stepper", replacement: fileURLToPath(new URL("../../packages/react-stepper/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-switch/styles", replacement: fileURLToPath(new URL("../../packages/react-switch/src/Switch.css", import.meta.url)) },
      { find: "@virtari-packages/react-switch", replacement: fileURLToPath(new URL("../../packages/react-switch/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-table/styles", replacement: fileURLToPath(new URL("../../packages/react-table/src/Table.css", import.meta.url)) },
      { find: "@virtari-packages/react-table/tokens", replacement: fileURLToPath(new URL("../../packages/react-table/src/Table.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-table", replacement: fileURLToPath(new URL("../../packages/react-table/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-tabs/styles", replacement: fileURLToPath(new URL("../../packages/react-tabs/src/Tabs.css", import.meta.url)) },
      { find: "@virtari-packages/react-tabs/tokens", replacement: fileURLToPath(new URL("../../packages/react-tabs/src/Tabs.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-tabs", replacement: fileURLToPath(new URL("../../packages/react-tabs/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-text/heading/styles", replacement: fileURLToPath(new URL("../../packages/react-text/src/Heading.css", import.meta.url)) },
      { find: "@virtari-packages/react-text/heading/tokens", replacement: fileURLToPath(new URL("../../packages/react-text/src/Heading.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-text/styles", replacement: fileURLToPath(new URL("../../packages/react-text/src/Text.css", import.meta.url)) },
      { find: "@virtari-packages/react-text/tokens", replacement: fileURLToPath(new URL("../../packages/react-text/src/Text.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-text", replacement: fileURLToPath(new URL("../../packages/react-text/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-textarea/styles", replacement: fileURLToPath(new URL("../../packages/react-textarea/src/Textarea.css", import.meta.url)) },
      { find: "@virtari-packages/react-textarea", replacement: fileURLToPath(new URL("../../packages/react-textarea/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-timeline/styles", replacement: fileURLToPath(new URL("../../packages/react-timeline/src/Timeline.css", import.meta.url)) },
      { find: "@virtari-packages/react-timeline/tokens", replacement: fileURLToPath(new URL("../../packages/react-timeline/src/Timeline.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-timeline", replacement: fileURLToPath(new URL("../../packages/react-timeline/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-toast/styles", replacement: fileURLToPath(new URL("../../packages/react-toast/src/Toast.css", import.meta.url)) },
      { find: "@virtari-packages/react-toast", replacement: fileURLToPath(new URL("../../packages/react-toast/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-toggle/styles", replacement: fileURLToPath(new URL("../../packages/react-toggle/src/Toggle.css", import.meta.url)) },
      { find: "@virtari-packages/react-toggle", replacement: fileURLToPath(new URL("../../packages/react-toggle/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-tooltip/styles", replacement: fileURLToPath(new URL("../../packages/react-tooltip/src/Tooltip.css", import.meta.url)) },
      { find: "@virtari-packages/react-tooltip/tokens", replacement: fileURLToPath(new URL("../../packages/react-tooltip/src/Tooltip.tokens.css", import.meta.url)) },
      { find: "@virtari-packages/react-tooltip", replacement: fileURLToPath(new URL("../../packages/react-tooltip/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-layout", replacement: fileURLToPath(new URL("../../packages/react-layout/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-header", replacement: fileURLToPath(new URL("../../packages/react-header/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-nav", replacement: fileURLToPath(new URL("../../packages/react-nav/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/react-sidebar", replacement: fileURLToPath(new URL("../../packages/react-sidebar/src/index.ts", import.meta.url)) },
      { find: "@virtari-packages/utils", replacement: fileURLToPath(new URL("../../packages/utils/dist/index.js", import.meta.url)) },
    ],
    conditions: ["style", "import", "module", "browser", "default"],
  },
  optimizeDeps: {
    exclude: ["@virtari-packages/primitives/switch", "@virtari-packages/primitives/checkbox", "@virtari-packages/primitives/radio-group"],
    // Stop Vite from auto-re-scanning when a consumer file is edited. The
    // re-scan sporadically bails on our workspace packages' subpath exports
    // (e.g. "@virtari-packages/react-data-table/styles") which throws a
    // "Failed to resolve import" overlay until the server is force-restarted.
    noDiscovery: true,
    // Pre-bundle these CJS/mixed deps so their ESM interop is correct — with
    // noDiscovery on, Vite won't auto-discover them, so list them here.
    include: [
      "react",
      "react-dom",
      "react-dom/client",
      "react/jsx-runtime",
      "i18next",
      "react-i18next",
      "@virtari-packages/primitives/accordion",
      "@virtari-packages/primitives/alert-dialog",
      "@virtari-packages/primitives/avatar",
      "@virtari-packages/primitives/collapsible",
      "@virtari-packages/primitives/dialog",
      "@virtari-packages/primitives/direction",
      "@virtari-packages/primitives/dropdown-menu",
      "@virtari-packages/primitives/label",
      "@virtari-packages/primitives/popover",
      "@virtari-packages/primitives/progress",
      "@virtari-packages/primitives/scroll-area",
      "@virtari-packages/primitives/select",
      "@virtari-packages/primitives/separator",
      "@virtari-packages/primitives/slider",
      "@virtari-packages/primitives/slot",
      "@virtari-packages/primitives/tabs",
      "@virtari-packages/primitives/toast",
      "@virtari-packages/primitives/toggle",
      "@virtari-packages/primitives/tooltip",
      "@internationalized/date",
      "@react-aria/calendar",
      "@react-aria/datepicker",
      "@react-aria/i18n",
      "@react-stately/calendar",
      "@react-stately/datepicker",
      "@dnd-kit/core",
      "@dnd-kit/sortable",
      "@dnd-kit/utilities",
      "@hookform/resolvers",
      "@tabler/icons-react",
      "@tanstack/react-table",
      "@tanstack/react-virtual",
      "cmdk",
      "libphonenumber-js",
      "react-dropzone",
      "react-hook-form",
      "zod",
      "is-hotkey",
      "slate",
      "slate-dom",
      "slate-react",
      "@yoopta/editor",
      "@yoopta/marks",
      "@yoopta/paragraph",
      "@yoopta/headings",
      "@yoopta/lists",
      "@yoopta/blockquote",
      "@yoopta/callout",
      "@yoopta/code",
      "@yoopta/divider",
      "@yoopta/link",
      "@yoopta/image",
      "@yoopta/video",
      "@yoopta/embed",
      "@yoopta/file",
      "@yoopta/table",
      "@yoopta/accordion",
      "@yoopta/tabs",
      "@yoopta/steps",
      "@yoopta/math",
      "@yoopta/mention",
      "@yoopta/emoji",
      "@yoopta/carousel",
      "@yoopta/table-of-contents",
      "@uiw/react-codemirror",
      "@codemirror/state",
      "@codemirror/view",
      "@codemirror/language",
      "@codemirror/commands",
      "@codemirror/search",
      "@codemirror/autocomplete",
      "@lezer/highlight",
      "@codemirror/lang-javascript",
      "@codemirror/lang-css",
      "@codemirror/lang-html",
      "@codemirror/lang-json",
      "@codemirror/lang-markdown",
      "@codemirror/lang-python",
      "@codemirror/lang-go",
      "@codemirror/lang-rust",
      "@codemirror/lang-sql",
      "@codemirror/lang-yaml",
      "@codemirror/lang-xml",
    ],
  },
});
