import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';
import { CopyButton } from '@virtari-packages/react-copy-button';
import '@virtari-packages/core';
import '@virtari-packages/tokens';
import '@virtari-packages/react-copy-button/styles';
const root=createRoot(document.getElementById('root')!);
const results:string[]=[];let calls:string[]=[],events=0,failures=0;
const check=(ok:boolean,name:string)=>results.push(`${ok?'PASS':'FAIL'} ${name}`);
const wait=()=>new Promise(resolve=>setTimeout(resolve,20));
Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{calls.push(text);}}});
flushSync(()=>root.render(<CopyButton text="sample" label="Copy" onClick={()=>events++} onCopied={()=>events++}/>));
document.querySelector<HTMLButtonElement>('button')!.click();await wait();
check(calls[0]==='sample'&&events===2,'consumer click composes with clipboard and success callback');
check(document.querySelector('[role="status"]')?.textContent==='Copied','success announced');
flushSync(()=>root.render(<CopyButton text="cancel" onClick={e=>e.preventDefault()}/>));
document.querySelector<HTMLButtonElement>('button')!.click();await wait();
check(calls.length===1,'preventDefault cancels clipboard');
flushSync(()=>root.render(<CopyButton text="disabled" disabled/>));
document.querySelector<HTMLButtonElement>('button')!.click();await wait();check(calls.length===1,'disabled blocks copying');
flushSync(()=>root.render(<CopyButton text=""/>));
document.querySelector<HTMLButtonElement>('button')!.click();await wait();check(calls.at(-1)==='','empty string is a valid copy');
Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject()}});
flushSync(()=>root.render(<CopyButton text="fail" errorLabel="Copy unavailable" onCopyError={()=>failures++}/>));
document.querySelector<HTMLButtonElement>('button')!.click();await wait();
check(failures===1&&document.querySelector('[role="status"]')?.textContent==='Copy unavailable','undefined rejection still produces accessible failure');
flushSync(()=>root.render(<CopyButton text="changed"/>));await wait();check(document.querySelector('[role="status"]')?.textContent==='','new text clears stale feedback');
let finish!:()=>void;
Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise<void>(resolve=>finish=resolve)}});
flushSync(()=>root.render(<CopyButton text="old" onCopied={()=>events++}/>));document.querySelector<HTMLButtonElement>('button')!.click();
flushSync(()=>root.render(<CopyButton text="new"/>));const previousEvents=events;finish();await wait();
check(events===previousEvents&&document.querySelector('[role="status"]')?.textContent==='','stale request cannot update new text or callbacks');
let buttonRef:HTMLButtonElement|null=null;
flushSync(()=>root.render(<CopyButton text="ref" ref={node=>{buttonRef=node;}}/>));
check(buttonRef===document.querySelector('button'),'forwarded ref targets native button');
flushSync(()=>root.render(<div>{(['2xs','xs','sm','md','lg'] as const).map(size=><CopyButton key={size} text="a" copyButtonSize={size} data-test-size={size}/>)}</div>));
for(const button of document.querySelectorAll<HTMLElement>('[data-test-size]')) {const r=button.getBoundingClientRect();check(r.width>=24&&r.height>=24&&Math.abs(r.width-r.height)<1,`${button.dataset.testSize} icon-only target is square and at least24px`);}
document.getElementById('results')!.textContent=results.join('\n');
