import type { EditorThemeClasses } from "lexical";

export const EDITOR_THEME: EditorThemeClasses = {
  characterLimit: "vds-editor-character-limit",
  code: "vds-editor-code-block",
  codeHighlight: {
    atrule: "vds-editor-code-token-attr",
    attr: "vds-editor-code-token-attr",
    boolean: "vds-editor-code-token-property",
    builtin: "vds-editor-code-token-selector",
    cdata: "vds-editor-code-token-comment",
    char: "vds-editor-code-token-selector",
    class: "vds-editor-code-token-function",
    "class-name": "vds-editor-code-token-function",
    comment: "vds-editor-code-token-comment",
    constant: "vds-editor-code-token-property",
    deleted: "vds-editor-code-token-deleted",
    doctype: "vds-editor-code-token-comment",
    entity: "vds-editor-code-token-operator",
    function: "vds-editor-code-token-function",
    important: "vds-editor-code-token-variable",
    inserted: "vds-editor-code-token-inserted",
    keyword: "vds-editor-code-token-attr",
    namespace: "vds-editor-code-token-variable",
    number: "vds-editor-code-token-property",
    operator: "vds-editor-code-token-operator",
    prolog: "vds-editor-code-token-comment",
    property: "vds-editor-code-token-property",
    punctuation: "vds-editor-code-token-punctuation",
    regex: "vds-editor-code-token-variable",
    selector: "vds-editor-code-token-selector",
    string: "vds-editor-code-token-selector",
    symbol: "vds-editor-code-token-property",
    tag: "vds-editor-code-token-property",
    unchanged: "vds-editor-code-token-unchanged",
    url: "vds-editor-code-token-operator",
    variable: "vds-editor-code-token-variable",
  },
  hr: "vds-editor-divider",
  hrSelected: "vds-editor-divider vds-editor-divider-selected",
  heading: {
    h1: "vds-editor-heading vds-editor-heading-h1",
    h2: "vds-editor-heading vds-editor-heading-h2",
    h3: "vds-editor-heading vds-editor-heading-h3",
    h4: "vds-editor-heading vds-editor-heading-h4",
    h5: "vds-editor-heading vds-editor-heading-h5",
    h6: "vds-editor-heading vds-editor-heading-h6",
  },
  link: "vds-editor-link",
  list: {
    ul: "vds-editor-list vds-editor-list-ul",
    ol: "vds-editor-list vds-editor-list-ol",
    checklist: "vds-editor-list vds-editor-list-check",
    listitem: "vds-editor-list-item",
    listitemChecked: "vds-editor-list-item vds-editor-list-item-checked",
    listitemUnchecked: "vds-editor-list-item vds-editor-list-item-unchecked",
    nested: {
      list: "vds-editor-list-nested",
      listitem: "vds-editor-list-item-nested",
    },
  },
  paragraph: "vds-editor-paragraph",
  mark: "vds-editor-comment-mark",
  markOverlap: "vds-editor-comment-mark-overlap",
  quote: "vds-editor-quote",
  table: "vds-editor-table",
  tableCell: "vds-editor-table-cell",
  tableCellHeader: "vds-editor-table-cell vds-editor-table-cell-header",
  tableRow: "vds-editor-table-row",
  tableScrollableWrapper: "vds-editor-table-scroll",
  text: {
    bold: "vds-editor-text-bold",
    code: "vds-editor-text-code",
    highlight: "vds-editor-text-highlight",
    italic: "vds-editor-text-italic",
    lowercase: "vds-editor-text-lowercase",
    uppercase: "vds-editor-text-uppercase",
    capitalize: "vds-editor-text-capitalize",
    strikethrough: "vds-editor-text-strikethrough",
    subscript: "vds-editor-text-subscript",
    superscript: "vds-editor-text-superscript",
    underline: "vds-editor-text-underline",
    underlineStrikethrough:
      "vds-editor-text-underline vds-editor-text-strikethrough",
  },
};
